const users = require("./users/users.service.js");
const upload = require("./upload/upload.service.js");
const role = require("./role/role.service.js");
const mailer = require("./mailer/mailer.service.js");
const refreshToken = require("./refresh-token/refresh-token.service.js");
const lessonCategory = require("./lesson-category/lesson-category.service.js");
const lesson = require("./lesson/lesson.service.js");
const friendship = require("./friendship/friendship.service.js");
const courseList = require("./course-list/course-list.service.js");
const courseCategory = require("./course-category/course-category.service.js");
const userInfo = require("./user-info/user-info.service.js");
const courseFeedback = require("./course-feedback/course-feedback.service.js");
const exercise = require("./exercise/exercise.service.js");
const userCourse = require("./user-course/user-course.service.js");
const lessonComment = require("./lesson-comment/lesson-comment.service.js");
const lessonExercise = require('./lesson-exercise/lesson-exercise.service.js');
const userFollow = require('./user-follow/user-follow.service.js');
// eslint-disable-next-line no-unused-vars
module.exports = function (app) {
  app.configure(users);
  app.configure(upload);
  app.configure(role);
  app.configure(mailer);
  app.configure(refreshToken);
  app.configure(lessonCategory);
  app.configure(lesson);
  app.configure(exercise);
  app.configure(courseList);
  app.configure(courseCategory);
  app.configure(friendship);
  app.configure(userInfo);
  app.configure(courseFeedback);
  app.configure(userCourse);
  app.configure(lessonComment);
  app.configure(lessonExercise);
  app.configure(userFollow);
};
